services:
  agri_db_test:
    image: mysql:5.7
    container_name: agrilite_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: biomart
    ports:
      - "3306:3306"
    volumes:
      - db_vol:/var/lib/mysql
      - "./biomart.sql:/docker-entrypoint-initdb.d/biomart.sql"

  agri_testfront:
    build:
      context: "./SourceCode"
      dockerfile: Dockerfile
    image: agribuzz:v4
    container_name: agrites4_front
    restart: always
    ports:
      - "8055:80"
    depends_on:
      - agri_db_test

volumes:
  db_vol:

